### ISSUE TITLE
Import and try code from sourceforge patches

### ISSUE THREAD

**Issue by skyghis** [skyghis/j-interop-ng#1]
Import and try code from [Sourceforge patches](https://sourceforge.net/p/j-interop/patches/) : 

- [x] [#1](https://sourceforge.net/p/j-interop/patches/1/)    Prevent buffer overruns in j-InteropDeps
- [ ] [#2](https://sourceforge.net/p/j-interop/patches/2/)    Modifications to j-Interop and j-Interopdeps
- [x] [#3](https://sourceforge.net/p/j-interop/patches/3/)    small fixes
- [x] [#4](https://sourceforge.net/p/j-interop/patches/4/)    JIComTransport fix for file descriptor leak
- [x] [#5](https://sourceforge.net/p/j-interop/patches/5/)    2.07: Support Java Cryptographic Service Provider Interface.
- [x] [#6](https://sourceforge.net/p/j-interop/patches/6/)    JIComTransport using single selector
- [x] [#7](https://sourceforge.net/p/j-interop/patches/7/)    patch for issue 3116666
- [ ] [#8](https://sourceforge.net/p/j-interop/patches/8/)    Improved Ref Counting to release all references correctly
- [ ] [#9](https://sourceforge.net/p/j-interop/patches/9/)    Add support for HKEY_PERFORMANCE_DATA to winreg
- [ ] [#10](https://sourceforge.net/p/j-interop/patches/10/)  UTF-16LE encoding of registry entries
- [ ] [#11](https://sourceforge.net/p/j-interop/patches/11/)  Timeout modifications to JiComOxidStub and JIComOxidRuntime
- [ ] [#12](https://sourceforge.net/p/j-interop/patches/12/)  Patch for forum thread: "Stopping all J-Interop threads"
- [ ] [#13](https://sourceforge.net/p/j-interop/patches/13/)  Adding IPv6 Support to JIComServer#decodeDualStringArray()
- [ ] [#14](https://sourceforge.net/p/j-interop/patches/14/)  Adding WMI implementation based on DCOM
- [ ] [#15](https://sourceforge.net/p/j-interop/patches/15/)  Fix for Add References bug
- [ ] [#16](https://sourceforge.net/p/j-interop/patches/16/)  DHCP Localhost IP address issue with JDK
- [ ] [#17](https://sourceforge.net/p/j-interop/patches/17/)  Windows 64-bit registry support
- [ ] [#18](https://sourceforge.net/p/j-interop/patches/18/)  Release all local components correctly
